#!/usr/bin/env python
"""Regenerate CORPORA.md from the corpora actually on disk.

Written as a script rather than a hand-maintained file because a manifest that
drifts from reality is worse than none -- it gets trusted.
"""
from __future__ import annotations
import gzip, json, pickle, sys
from pathlib import Path

ROOT = Path("/home/mogan/preprocessed/molplatte")
OUT = Path(__file__).resolve().parent.parent / "CORPORA.md"

#: What each corpus is FOR. Anything on disk but absent here is reported as
#: undocumented, which is the state that should prompt either a note or a delete.
PURPOSE = {
    "flavordb-only":             ("active", "FlavorDB alone. Every molecule carries a measured flavor label, so the condvec is dense. Small; use for conditioning experiments where label coverage matters more than scale."),
    "coconut-only":              ("active", "COCONUT alone. Natural-product chemistry with almost no flavor labels. The contrast arm for anything claiming a flavor effect."),
    "coconut-flavordb-full":     ("active", "Both sources, unfiltered. The default pretraining corpus."),
    "coconut-flavordb-filtered": ("active", "Both sources, COCONUT restricted to the odorant physicochemical envelope (MW 108-290, logP 0.4-4.5, TPSA<=53) derived from FlavorDB's own non-imputed labels, plus every known-flavor compound. 10.6% known-flavor density against a 0.62% base rate -- 17x enriched. Intended for pocket finetuning and flavor conditioning."),
    "coconut-flavordb_v7":       ("superseded", "Same content as coconut-flavordb-full. Retained because the three-arm condvec shuffle test was run against it; deleting it orphans those results."),
        }

def build_tag(meta):
    p = meta.get("decomposition_params") or {}
    r = p.get("ratio")
    return (f"r{str(round(r,3)).replace('0.','')}"
            f"-m{p.get('min_rgroup_atoms','?')}"
            f"-h{meta.get('graph_hash_version','?')}"
            f"-{meta.get('condvec_mode','?')}{meta.get('condvec_dim','')}")

def scan():
    out = []
    for d in sorted(ROOT.iterdir()):
        if not d.is_dir() or d.name in ("logs", "annotations"):
            continue
        m = d / "naveja_recap" / "__meta__.json"
        if not m.is_file():
            continue
        meta = json.load(m.open())
        v = d / "naveja_recap" / "rgroup_vocab.pkl.gz"
        vocab = eff = None
        if v.is_file():
            with gzip.open(v, "rb") as fh:
                pr = pickle.load(fh)["provenance"]
            vocab, eff = pr.get("n_distinct"), pr.get("effective_size")
        size = sum(f.stat().st_size for f in (d / "naveja_recap").rglob("*.pt"))
        out.append(dict(name=d.name, meta=meta, vocab=vocab, eff=eff,
                        gb=size / 1024**3, tag=build_tag(meta)))
    return out

def main():
    rows = scan()
    tags = {r["tag"] for r in rows}
    L = []
    L.append("# Corpora\n")
    L.append("Generated by `scripts/write_corpora_manifest.py` from what is on disk. "
             "Do not hand-edit -- regenerate it.\n")
    L.append("## Naming\n")
    L.append("Two orthogonal axes, which earlier versions conflated:\n")
    L.append("- **content** -- which sources and which filter (`coconut-flavordb-filtered`)")
    L.append("- **build tag** -- the settings that determine whether two corpora are "
             "COMPARABLE (`r333-m2-h4-flavor24`): decomposition ratio, "
             "`min_rgroup_atoms`, `HASH_VERSION`, condvec mode and width\n")
    L.append("Two corpora may be compared only if their build tags match. The old "
             "`v3..v7` names were sequential fixes, not content variants, and could not "
             "express that distinction.\n")
    L.append("A `HASH_VERSION` mismatch is enforced at load time: the stored "
             "`rgroup_hashes`, the library keys and the loss's multi-positive grouping "
             "must all agree, and a mismatch would degrade retrieval silently rather "
             "than fail.\n")
    L.append("## On disk\n")
    L.append("| corpus | status | records | vocab | eff. | size | build tag |")
    L.append("|---|---|---:|---:|---:|---:|---|")
    for r in rows:
        st, _ = PURPOSE.get(r["name"], ("UNDOCUMENTED", ""))
        L.append(f"| `{r['name']}` | {st} | {r['meta'].get('n_records',0):,} | "
                 f"{r['vocab'] or 0:,} | {r['eff'] or 0:.0f} | {r['gb']:.1f} GB | "
                 f"`{r['tag']}` |")
    L.append("")
    L.append("## What each is for\n")
    for r in rows:
        st, why = PURPOSE.get(r["name"], ("UNDOCUMENTED",
                 "Not described in write_corpora_manifest.py. Either document it or delete it."))
        L.append(f"### `{r['name']}` — {st}\n")
        L.append(why + "\n")
    L.append("## Shared build settings\n")
    L.append("All corpora above were built with the same decomposition, which is why "
             "their build tags agree:\n")
    L.append("```")
    L.append("method            naveja_recap  (RECAP bonds -> fragment tree -> connected")
    L.append("                                 subtrees as cores)")
    L.append("core ratio        1/3           dominates 0.4 on every axis at equal cost")
    L.append("max_cores         4")
    L.append("min_rgroup_atoms  2             removes single-atom R-groups; effective")
    L.append("                                vocabulary 46 -> 889")
    L.append("HASH_VERSION      4             total_num_hs, is_in_ring; hybridization")
    L.append("                                dropped (parent-context leakage)")
    L.append("condvec           flavor(24)    molecule-level, from measurement /")
    L.append("                                literature / physics -- never from structure")
    L.append("```")
    L.append("")
    L.append("## Condition vector\n")
    L.append("24 bits: 5 taste primaries, 17 odor classes, `odorless`, `unknown`. "
             "Sources, in priority order, all exogenous to the molecular graph:\n")
    L.append("1. **measured** — FlavorDB by InChIKey (11,262 keys)")
    L.append("2. **mined** — LLM annotations at the `documented` tier ONLY, i.e. literature "
             "recall with a named source; 96.4% cite Good Scents, BitterDB or FEMA "
             "(1,927 compounds). `structural` and `close_analog` tiers are excluded "
             "because both are inferred from the graph.")
    L.append("3. **physics** — `odorless` where MW>350 and no sugar; a claim about "
             "volatility, not about missing data.\n")
    L.append("An all-zero vector is never emitted. Zero would mean \"no flavor\", and "
             "silently labelling 94% of the corpus flavourless would teach source "
             "provenance rather than flavour -- the same failure as the original 97-bit "
             "fragment condvec, which was computed from the intact molecule and so "
             "contained the R-group being predicted.\n")
    L.append("Shuffle test on `coconut-flavordb_v7` (25 epochs, logQ on):\n")
    L.append("```")
    L.append("no condition          H@1 0.3050")
    L.append("PERMUTED condition    H@1 0.3098   +1.6%  <- capacity effect")
    L.append("real condition        H@1 0.3164   +3.7%")
    L.append("```")
    L.append("The real-minus-permuted gap is 2.1% (~0.007 absolute), against a "
             "seed-to-seed spread of +-0.015. So the condvec does NOT leak -- a leak "
             "would show a large gap -- but it is also not demonstrably helping. "
             "Settling that needs seed replicates on all three arms.\n")
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT}  ({len(rows)} corpora, {len(tags)} distinct build tag(s))")
    for r in rows:
        if r["name"] not in PURPOSE:
            print(f"  UNDOCUMENTED: {r['name']}")

if __name__ == "__main__":
    main()
